spring:
  r2dbc:
    driver-class-name: org.postgresql.Driver
    url: r2dbc:postgresql://localhost:5432/orderdetails
    username: postgres
    password: Vaifery111

  main:
    allow-circular-references: true
  application:
    name: order

server:
  port: 7003